kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: yml-nginx-deployment
spec:
  replicas: 3
  strategy: Recreate
  selector:
    matchLabels:
      deploy: example
  template:
    metadata:
      labels:
        deploy: example
    spec:
      # $.spec.template.spec.securityContext.runAsUser any equal 0
      securityContext:
        runAsUser: 0
      containers:
        - name: nginx
          image: nginx:1.7.9
          securityContext:
            # $.spec.template.spec.containers[*].securityContext.readOnlyRootFilesystem exists and $.spec.template.spec.containers[*].securityContext.readOnlyRootFilesystem any false
            readOnlyRootFilesystem: false
            # $.spec.template.spec.containers[*].securityContext.privileged any true
            privileged: true
            # $.spec.template.spec.containers[*].securityContext.runAsNonRoot equals false
            runAsNonRoot: false
            capabilities:
              drop:
                # $.spec.template.spec.containers[*].securityContext.capabilities.drop exists and not $.spec.templates.spec.containers[*].securityContext.capabilities.drop[*] contains ALL
                - SYS_ADMIN
              add:
                # $.spec.template.spec.containers[*].securityContext.capabilities exists and $.spec.template.spec.containers[*].securityContext.capabilities.add[*] is member of (FSETID, SETUID, SETGID,SYS_CHROOT,SYS_PTRACE,CHOWN,NET_RAW,NET_ADMIN,SYS_ADMIN,NET_BIND_SERVICE)
                - NET_BIND_SERVICE
        - name: nginx
          image: nginx:1.8.0
          securityContext:
            # $.spec.template.spec.containers[*].securityContext.runAsUser < 9999
            runAsUser: 9998
      # $.spec.template.spec.hostIPC is true
      hostIPC: true
      # $.spec.template.spec.hostPID is true
      hostPID: true
      # $.spec.template.spec.hostNetwork is true
      hostNetwork: true
  volumeClaimTemplates:
    - spec:
        accessModes: ReadOnlyMany
        # $.spec.volumeClaimTemplates[*].spec.accessModes contains ReadWriteMany
        accessModes: ReadWriteMany



# Modified [k8s_all_issues.yaml] on [2020-11-10 23:12:35.070678]
# Modified [k8s_all_issues.yaml] on [2020-11-10 23:14:56.506601]
# Modified [k8s_all_issues.yaml] on [2020-11-10 23:19:32.595220]
# Modified [k8s_all_issues.yaml] on [2020-11-14 13:51:50.404650]
# Modified [k8s_all_issues.yaml] on [2020-11-14 18:58:28.309982]
# Modified [k8s_all_issues.yaml] on [2020-11-14 19:02:50.638593]
# Modified [k8s_all_issues.yaml] on [2020-11-14 19:07:16.765805]
# Modified [k8s_all_issues.yaml] on [2020-11-14 19:16:16.526258]
# Modified [k8s_all_issues.yaml] on [2020-11-14 19:54:41.622282]
# Modified [k8s_all_issues.yaml] on [2020-11-14 20:16:52.425079]